const stories = [
{
id:'italy',name:'意大利独行',subtitle:'旅行 · 经历 · 独立',title:'A trip that became my own',category:'TRAVEL & INDEPENDENCE',summary:'从第一天累到想回家，到在古迹前舍不得离开。',
facts:['独自去意大利，第一天太累，甚至想回家。','去过佛罗伦萨、马泰拉、罗马和梵蒂冈。','看过阿诺河日落、马泰拉的暮色。','在斗兽场前徘徊很久，觉得走到这里并不容易。'],
core:["I travelled around Italy on my own this summer, visiting places including Florence, Matera and Rome. It sounds wonderful when I list the places, but the beginning was quite a shock. On the first day, I was so tired that I actually wanted to go home. There was a big difference between imagining a solo trip and being the person responsible for getting through it.","What stayed with me were quite specific moments: watching the sunset over the Arno, seeing the evening colours change in Matera, and standing in front of the Colosseum. I spent a long time there. Reaching it felt significant, partly because of the journey itself and partly because travelling abroad had meant so much to me."],
outline:['Italy · this summer · travelling alone','first day exhausted → wanted to go home','Arno sunset · Matera colours · Colosseum','the practical journey + personal meaning'],
phrases:[['There was a big difference between…','用来展开期待与实际的差别'],['What stayed with me was…','引出真正记住的细节'],['I was responsible for…','说明自己承担的事情'],['It meant a great deal to me.','比反复说 very important 更自然']],
topics:[
{label:'难忘的旅行',question:'Describe a memorable trip you took.',cues:['where and when you went','what you did there','why you still remember it'],opening:"I'd like to talk about my trip to Italy, especially the way my feelings about travelling alone changed while I was there.",focus:'以旅程为主线。保留开头的不适应，再用两三个具体画面解释为什么难忘。',detail:"The contrast is what makes the trip so memorable for me. At first, I was counting the difficulties; later, I was collecting moments I didn't want to end.",ending:"So I remember it as much for that change in perspective as for the places themselves. It felt like a trip I had really made my own.",key:'memorable trip → changing feelings'},
{label:'想再去的地方',question:'Describe a place you have visited and would like to return to.',cues:['where the place is','what you did on your first visit','why you would like to go back'],opening:"A place I'd love to return to is Rome. I visited it as part of a solo trip around Italy, and I still think about its ancient buildings.",focus:'主角收窄为 Rome；佛罗伦萨和马泰拉只交代背景，把时间留给斗兽场与重访理由。',detail:"If I went back to Rome, I'd give myself more time around the ancient sites. I'd like to spend less energy worrying about getting around and more time simply taking in what was in front of me.",ending:"I wouldn't be trying to repeat the whole trip. I'd want a slower visit to Rome, with more room to enjoy the details I was too overwhelmed to notice.",key:'Rome → Colosseum → slower return',replaceCore:["I went to Rome this summer as part of a trip around Italy on my own. By that point, I'd already experienced how tiring independent travel could be. On the first day of the trip, I had actually wanted to go home. Rome brought its own challenges too: I felt nervous on the metro, even though I was excited about exploring the city.","The place that really stayed with me was the Colosseum. I stood in front of it for a long time, and I found it hard to leave. It wasn't just an impressive ancient building. Being there reminded me how much it had taken to reach that point, both practically and personally."]},
{label:'走出舒适区',question:'Describe a time you did something outside your comfort zone.',cues:['what you did','what made it unfamiliar','how you felt afterwards'],opening:"One experience that pushed me out of my comfort zone was travelling around Italy by myself. I was excited about it, but I wasn't comfortable all the time.",focus:'强调不习惯在哪里、自己承担了什么。景点作支撑，不逐站介绍。',detail:"The difficult part was accepting that feeling uncomfortable didn't automatically mean I had made a bad decision. I could be tired or nervous and still find something worthwhile in the day.",ending:"I came away feeling more willing to do things before I felt completely ready. I still like having a plan, but I don't expect every moment to feel easy.",key:'unfamiliar → responsibility → more willing'},
{label:'期待已久的事',question:'Describe something you had wanted to do for a long time.',cues:['what you wanted to do','why you wanted to do it','what the experience was like'],opening:"For a long time, I'd wanted to travel abroad and see places I had only known through pictures. My trip to Italy gave me the chance to do that.",focus:'突出过去的愿望与真正到达后的感受；不虚构订票时间或存钱年数。',detail:"The interesting thing was that the reality wasn't as effortless as the idea in my head. I had imagined the beautiful places, but not quite how tired I would sometimes feel between them.",ending:"Even so, standing in those places made the wish feel real. The difficult moments are part of the memory now, rather than a reason to wish I hadn't gone.",key:'long-held wish → real experience → mixed feelings'}
],part3:[{q:'Why do some people prefer travelling alone?',guide:'观点 → 自主安排的原因 → 代价；不要继续复述自己的行程。',a:"One reason is the freedom to make small decisions without negotiating every detail. You can spend longer somewhere that interests you. The trade-off is that all the practical responsibility falls on you, so I think it suits some people better than others."},{q:'Can travel change the way people think?',guide:'解释改变如何发生，再补充条件。',a:"It can, especially when everyday experiences challenge someone's assumptions. Even using public transport in an unfamiliar place can reveal how much we take for granted at home. But it depends on how someone travels; simply moving between famous attractions doesn't necessarily lead to much reflection."}]
},
{
id:'david',name:'在《大卫》面前',subtitle:'艺术 · 地点 · 感动',title:'When a picture became real',category:'ART & EMOTION',summary:'穿过长廊，看见穹光下的《大卫》，眼泪突然掉下来。',
facts:['在佛罗伦萨亲眼看到米开朗基罗的《大卫》。','转到长廊时，看到尽头的雕像沐浴在穹光下。','当时情绪强烈，哭了。','旅行中用上了之前准备的艺术史知识。'],
core:["During my trip to Florence, I went to see Michelangelo's David. I'd already seen pictures of it, so I knew what the sculpture looked like. But recognising an image and actually standing in front of the work turned out to be very different experiences.","The moment I remember most clearly is turning into the gallery and seeing David at the end, with light falling on it from above. I became so emotional that I cried. That surprised me. I had some art-history knowledge to draw on, but my first response wasn't an academic one. It was much more immediate than that."],
outline:['Florence · Michelangelo’s David','familiar from pictures ≠ being there','turn into gallery → light from above → tears','knowledge in the background · immediate feeling'],
phrases:[['Seeing it in person','亲眼见到；适用于艺术品、建筑和演出'],['It caught me off guard.','它让我始料未及；这里指情绪反应'],['I had some knowledge to draw on.','有一些已有知识可以用上'],['My first response was…','描述第一反应，不急着堆形容词']],
topics:[
{label:'喜欢的艺术品',question:'Describe a work of art that impressed you.',cues:['what the work is','where you saw it','what impressed you about it'],opening:"The work of art I'd choose is Michelangelo's David, which I saw in Florence. It's one of the few artworks that has made me cry.",focus:'以作品及观看感受为中心；用光线、空间和自己的反应说明 impressed。',detail:"I think the setting mattered as well as the sculpture itself. The view along the gallery gave me a moment to take it in before I tried to analyse anything.",ending:"What impressed me wasn't just its fame. It was the way something I already recognised could still produce such an unexpected reaction when I finally saw it in person.",key:'artwork → setting → personal reaction'},
{label:'有趣的建筑',question:'Describe a building you visited that you found interesting.',cues:['what kind of building it is','what you saw inside','why the visit interested you'],opening:"I'd like to describe the gallery in Florence where I saw Michelangelo's David. What interested me most was how the interior shaped the experience of seeing the sculpture.",focus:'题目主角是建筑内部：强调长廊、尽头和采光。只适配一般建筑题，不套到建筑外观或设计者题。',detail:"I noticed the relationship between the long gallery, the position of the sculpture and the light above it. Together, they directed my attention towards the same point without anyone having to explain where to look.",ending:"That's why the building stayed in my mind. I remember it through the way it presented the artwork, rather than through a list of architectural facts.",key:'gallery interior → layout → light'},
{label:'感到激动的时刻',question:'Describe a time you felt a strong positive emotion.',cues:['when and where it happened','what caused the feeling','why the moment was special'],opening:"A moment when I felt unexpectedly moved was seeing David in Florence. I knew I wanted to see it, but I hadn't expected such a strong emotional reaction.",focus:'重心放在情绪怎样发生；艺术史背景压到一句，不变成作品介绍。',detail:"I couldn't have given a neat explanation at the time. There was the artwork, of course, but also the feeling that I had actually made it to a place I had looked forward to visiting.",ending:"I still find it difficult to separate those feelings completely. What I know is that it was a very personal moment, even though I was looking at something famous around the world.",key:'anticipation → unexpected tears → personal meaning'},
{label:'文化体验',question:'Describe a cultural experience you enjoyed.',cues:['what the experience was','what you already knew about it','what you gained from the experience'],opening:"A cultural experience I really valued was seeing David during my visit to Florence. It gave me a much more direct connection with art than looking at reproductions had.",focus:'突出之前的知识如何与亲眼观看连接；少讲交通行程。',detail:"The art-history material I'd prepared gave me a starting point. But being there also reminded me that cultural experiences don't have to be entirely intellectual; sometimes the emotional response comes first.",ending:"That combination made the visit valuable to me. I could connect it with things I'd learned, while still allowing myself to react without having a polished interpretation ready.",key:'prior knowledge → encounter → connection'}
],part3:[{q:'Do people need to understand art to enjoy it?',guide:'先回答不一定，再区分即时感受与背景知识。',a:"Not necessarily. A person's first response might be to colour, scale or atmosphere, and that can be meaningful on its own. Background knowledge can deepen the experience by revealing details they would otherwise miss, but I wouldn't treat it as an entrance requirement."},{q:'Will digital images replace visits to museums?',guide:'承认数字形式的价值，再解释实体体验的差异。',a:"Digital images make art much more accessible and can be excellent for studying details. However, they don't fully reproduce scale, space or the way a work is displayed. I think the two experiences can complement each other rather than one completely replacing the other."}]
},
{
id:'matera',name:'马泰拉的上坡路',subtitle:'困难 · 坚持 · 风景',title:'The uphill part of the journey',category:'CHALLENGE & PLACE',summary:'一个人拖着箱子走了两公里上坡，也记住了从橙色变成群青色的天。',
facts:['在马泰拉独自拉箱子走了约两公里上坡。','这段路很累，是旅行里具体的困难。','看见暮色由橙色、粉色逐渐变为群青色。','没有已知的迷路、陌生人帮助或错过末班车情节。'],
core:["When I was in Matera during my solo trip to Italy, I had to pull my suitcase uphill for about two kilometres. It was a very practical problem: I was on my own, I had my luggage with me, and the route was physically tiring. It's the sort of detail that disappears when a trip is reduced to a few attractive photographs.","Another memory I have of Matera is the evening light. The colours shifted from orange to pink and eventually to a deep blue. Those two memories sit next to each other for me: the effort of getting around and the beauty of the place. I can't really separate the city from the experience of moving through it."],
outline:['Matera · alone · suitcase','about two kilometres uphill · physically tiring','evening: orange → pink → deep blue','effort and beauty in the same memory'],
phrases:[['pull my suitcase uphill','具体动作比 a difficult experience 更有画面'],['It was physically tiring.','准确区分体力疲劳与精神压力'],['The colours shifted from… to…','描述渐变，不只说 beautiful'],['Those memories sit next to each other.','把两种不同感受自然联系起来']],
topics:[
{label:'遇到的困难',question:'Describe a difficult situation you experienced.',cues:['where you were','what made the situation difficult','how you feel about it now'],opening:"A difficult situation I remember was getting around Matera with my suitcase. It wasn't a dramatic emergency, but at the time it was genuinely hard work.",focus:'把困难说具体：独自、行李、距离、坡度。只讲实际经历，不添加获救情节。',detail:"The distance alone doesn't tell the whole story. Pulling luggage changes how you experience a road, and being alone meant that I had to deal with the whole stretch myself.",ending:"Looking back, I remember it as an uncomfortable but very real part of independent travel. It gave me a more practical understanding of what a journey can involve.",key:'problem → concrete difficulty → reflection'},
{label:'坚持完成的事',question:'Describe something difficult that you managed to do.',cues:['what you needed to do','why it was difficult','how you felt about the experience'],opening:"Something difficult I managed to do was pull my suitcase up a long uphill route in Matera while travelling alone. It was a small achievement, but a memorable one.",focus:'突出自己完成了这段路。不要编造停下来喝水、数台阶等未确认动作。',detail:"It wasn't an achievement anyone would put on a certificate. Still, dealing with the unglamorous parts of a trip matters, because there's no way to enjoy a place without getting through some of the practical work.",ending:"That's what made it satisfying to look back on. I had dealt with something tiring on my own, and the memory became part of my attachment to Matera.",key:'task → effort → small achievement'},
{label:'美丽的地方',question:'Describe a beautiful place you have visited.',cues:['where the place is','what it looked like','why you remember it'],opening:"A beautiful place I'd like to describe is Matera in Italy. The image that comes back to me most often is its changing colour in the evening.",focus:'以暮色为主体，上坡路仅作对比背景；主线换成视觉描述。',detail:"What appealed to me was that it didn't stay the same. The orange and pink gradually gave way to a much deeper blue, so the atmosphere of the place seemed to change with the light.",ending:"I think that's why I remember it so vividly. The physical effort of the visit was real, but so was the pleasure of watching that slow change in colour.",key:'Matera → changing colours → atmosphere'},
{label:'难忘的一天',question:'Describe a day during a trip that you remember well.',cues:['where you were','what made the day distinctive','why it has stayed in your memory'],opening:"I'd choose the day I had to take my suitcase uphill in Matera. Of all the moments from my Italy trip, that stretch of road has stayed remarkably clear in my memory.",focus:'围绕上坡这一天讲；暮色是同一城市的另一段回忆，不强行说发生在同一天。',detail:"I remember the day through that physical experience more than through a detailed timetable. The evening colours are another memory of Matera, and together they shape the way I think about the place.",ending:"For me, a memorable travel day doesn't have to be comfortable from beginning to end. Sometimes a difficult detail is precisely what stops it from blending into all the others.",key:'specific day → physical memory → why memorable'}
],part3:[{q:'Why do people sometimes value difficult experiences?',guide:'说明付出与记忆的联系，不把困难一律美化。',a:"One reason is that effort can make an experience feel more personal. People remember what they had to work through. That doesn't mean every difficulty is beneficial, though. Some problems are simply exhausting, and we don't need to pretend that suffering is necessary for a worthwhile experience."},{q:'How can cities make travel easier for visitors?',guide:'提出具体措施并解释使用场景。',a:"Clear signs and reliable information about walking routes would help, especially where there are steep slopes or steps. Visitors with luggage may need different information from someone taking a casual walk. Good local transport can also make a destination accessible to a wider range of people."}]
},
{
id:'research',name:'从 MILP 到具身 AI',subtitle:'决定 · 学科 · 未来',title:'Finding the questions I care about',category:'DECISION & CURIOSITY',summary:'从抽象优化问题，走向能够感知、推理并与真实世界互动的 AI。',
facts:['清华计算机本科，早期接触 MILP / optimization。','现在关注 multimodal AI、MLLM、robotics / embodied AI。','希望研究能感知、推理并与真实世界互动的系统。','暑期参与 physical AI 团队，并与同学合作做 benchmark。'],
core:["I'm studying computer science, and my earlier research interests involved optimisation, including mixed-integer linear programming. In everyday language, that's about finding a good solution while respecting a set of constraints. I could appreciate the structure of those problems, but I became increasingly interested in questions about how AI understands the world around it.","That led me towards multimodal and embodied AI. The broad idea is to build systems that can work with information such as language and video, and, in embodied settings, connect understanding with actions in the physical world. During the summer, I joined a team working on physical AI and started collaborating on a benchmark. That has given me a concrete way to explore the area."],
outline:['CS student · optimisation background','MILP = solutions under constraints','new interest: language + video + physical world','summer team · benchmark · still learning'],
phrases:[['I became increasingly interested in…','渐进的兴趣变化，不编造顿悟时刻'],['In everyday language, that means…','把术语解释给非本专业听众'],['That led me towards…','自然衔接原因与方向变化'],['a concrete way to explore the area','把抽象兴趣落到正在做的工作']],
topics:[
{label:'重要决定',question:'Describe an important decision you made about your studies.',cues:['what the decision was','why you made it','how it has affected you'],opening:"An important decision I made was to shift my research focus from optimisation towards multimodal and embodied AI. It changed the kinds of questions I wanted to spend time on.",focus:'讲为什么转向以及已经做了什么。原方向简要解释，不贬低它来制造反差。',detail:"The attraction was the connection with perception and interaction. I wanted to think about what a system could understand from the world, not only how to formulate a mathematical objective.",ending:"I'm still early in the process, so I wouldn't present it as a finished success story. What has changed is that I now have a clearer sense of the questions that keep me curious.",key:'decision → reason → present effect'},
{label:'感兴趣的学科',question:'Describe a subject you would like to learn more about.',cues:['what the subject is','how you became interested in it','what you would like to understand better'],opening:"A subject I'd like to learn more about is embodied AI. In simple terms, it's about AI systems that can connect their understanding with actions in the physical world.",focus:'学科本身是主角。用语言、视频、动作解释，不连续抛 MILP、MLLM 等缩写。',detail:"What I'd particularly like to understand is how we can tell whether a system really understands a situation. Producing a plausible answer and acting appropriately in a changing environment are different challenges.",ending:"That mix of perception, reasoning and action is what keeps me interested. There are enough unanswered questions that I can imagine spending a long time learning about it.",key:'subject → accessible explanation → curiosity'},
{label:'未来目标',question:'Describe a goal you would like to achieve in the future.',cues:['what the goal is','why it matters to you','what you are doing to work towards it'],opening:"One goal I have is to pursue a PhD and develop my research in multimodal or embodied AI. I want to become better at turning interesting questions into work that can actually be evaluated.",focus:'未来目标要说成计划。将暑期进组和 benchmark 作为正在采取的步骤，不写成已经录取或发表。',detail:"My immediate task is to build research experience and learn how to ask a precise question. Working on a benchmark helps because it forces me to think about what evidence would support a claim.",ending:"The PhD is a longer-term goal. Right now, I can make progress by doing the current work carefully and finding out which problems I want to commit to.",key:'PhD goal → motivation → current steps'},
{label:'学习上的变化',question:'Describe a change you made that affected the way you learn.',cues:['what you changed','what you did differently','why the change matters'],opening:"A change that affected the way I learn was moving into multimodal and embodied AI research. I started paying more attention to what a system can understand in a concrete situation.",focus:'重心放在学习关注点：从形式化问题到观察和评估真实场景；不要只换开头后继续讲决定。',detail:"The benchmark work has made evaluation part of my learning. When I read about a model's abilities, I want to know what the test asks it to do and whether the task really measures the ability being claimed.",ending:"That has made my learning more question-driven. I still need technical foundations, but I also need to connect them with a clear reason for running an experiment.",key:'change → evaluation questions → learning approach'}
],part3:[{q:'Should students choose practical subjects over theoretical ones?',guide:'解释两者用途，再给出选择条件。',a:"I don't think it has to be a strict choice. Theory helps people recognise the structure behind a problem, while practical work shows where an idea meets real constraints. The balance should depend on the student's aims and stage of learning, rather than the assumption that one is always more valuable."},{q:'Why do people change their career or study plans?',guide:'从个人原因扩大到普遍原因。',a:"Sometimes people discover an interest they couldn't have predicted before trying the work. They may also find that the daily reality of a field differs from its image. Changing direction can be sensible when it follows a better understanding of the work, rather than just a short period of frustration."}]
},
{
id:'socialflux',name:'我的 SocialFlux',subtitle:'项目 · 创意 · 技术',title:'Can AI follow a change of heart?',category:'PROJECT & IDEAS',summary:'把长期情绪理解、状态变化和不同选择的后果，变成能评测的问题。',
facts:['项目现在叫 SocialFlux，曾用名 EmoTree-Bench。','研究长期互动中的情绪理解、状态变化和反事实推理。','用共享历史下的不同选择比较后续影响。','项目仍在开发；没有确认的发表、获奖或完成扩量结果。'],
core:["I'm developing a research project called SocialFlux. The basic question is whether an AI system can follow how someone's emotions and relationships change over a conversation. Understanding a single sentence is only part of that problem. What happened earlier may affect what a person means now.","The project is designed as a benchmark, which is essentially a structured set of tasks for evaluating models. One idea is to keep the earlier conversation the same, introduce different possible actions, and compare their consequences. That lets us ask whether a model can reason about how one choice might lead to a different outcome from another."],
outline:['SocialFlux · research project in progress','emotions + relationships across a conversation','benchmark = structured evaluation tasks','same history → different actions → consequences'],
phrases:[['What happened earlier may affect…','说明历史信息为何重要'],['a structured set of tasks','向普通听众解释 benchmark'],['keep the earlier conversation the same','口语化解释受控比较'],['reason about possible consequences','说清模型要做什么，不堆研究术语']],
topics:[
{label:'正在做的项目',question:'Describe a project you are working on.',cues:['what the project is','what you are trying to do','why it interests you'],opening:"I'd like to talk about SocialFlux, a research project I'm working on about AI and emotional understanding. It's still in development, which is part of why I have so much to say about it.",focus:'项目目的 → 核心任务 → 自己为什么投入。明确在开发，不假装已经完成。',detail:"What interests me is the gap between recognising an emotional word and understanding an interaction. Someone can sound calm in one sentence even when the history suggests that something more complicated is going on.",ending:"I'm trying to make those questions specific enough to evaluate. I find that process interesting because it combines a technical problem with situations that feel recognisably human.",key:'project → purpose → personal interest'},
{label:'有创意的想法',question:'Describe an idea you had that you found interesting.',cues:['what the idea was','what problem it addressed','how you are developing it'],opening:"An idea I've been developing is to evaluate AI by comparing different choices within the same conversation history. It forms part of my project, SocialFlux.",focus:'突出共享过去、改变选择的想法。不要把“世界首次”或独占贡献当作事实。',detail:"The useful feature is the shared starting point. If the earlier interaction is different in every example, it becomes harder to explain why the outcomes differ. Keeping that background fixed makes the comparison more focused.",ending:"I like the idea because it turns a broad question about emotional intelligence into something more concrete. The challenge now is to make the examples and evaluation work well.",key:'idea → shared starting point → focused comparison'},
{label:'想了解的技术',question:'Describe a technology you would like to understand better.',cues:['what the technology is','what it could be used for','what you want to learn about it'],opening:"I'd like to understand AI systems for analysing conversations more deeply, especially how they use earlier context to interpret someone's current feelings. My project, SocialFlux, is one way I'm exploring that.",focus:'技术能力与自己的疑问是主线；不宣称它能读心、诊断情绪或预测真实人物。',detail:"I'm particularly interested in the limits of these systems. A confident explanation can sound convincing, but that doesn't by itself show that the model has used the relevant history or understood the consequences of a choice.",ending:"That's why I want to understand how these abilities can be evaluated carefully. For me, learning about a technology also means finding out where its apparent competence breaks down.",key:'technology → abilities → limits to investigate'},
{label:'有挑战的学习任务',question:'Describe a challenging task related to your studies.',cues:['what the task involves','why it is challenging','what you are learning from it'],opening:"A challenging task in my studies is designing an evaluation for emotional understanding in AI. I'm working on it through SocialFlux, and the difficulty is making a broad concept testable.",focus:'讲任务设计为什么难，以及目前学到什么；不虚构调试时长或实验通过率。',detail:"The difficult part is deciding what a good answer should demonstrate. It isn't enough for a response to sound sympathetic. The evaluation needs to distinguish that from understanding the history and the possible effects of an action.",ending:"It's teaching me to be more precise about research claims. Before asking which model performs best, I need to be clear about what the task actually measures.",key:'task → defining evidence → lesson'}
],part3:[{q:'Can AI understand human emotions?',guide:'先区分识别线索与拥有感受，再给有限判断。',a:"AI can identify patterns in what people say and sometimes produce a useful interpretation. But that doesn't show that it experiences emotions or understands a person's situation in the way another human might. I would judge it by specific, observable abilities rather than making a single broad claim."},{q:'What makes a research project valuable?',guide:'问题、证据、可供他人使用的结果。',a:"A valuable project should ask a question that matters and provide evidence that helps answer it. The result doesn't always have to be a spectacular new system. A careful evaluation or a finding about where an existing method fails can also give other researchers something useful to build on."}]
},
{
id:'letter',name:'从梵蒂冈寄出的信',subtitle:'文字 · 感谢 · 表达',title:'More than a message home',category:'WRITING & CONNECTION',summary:'从去多哈的第一程就想写，最后想从梵蒂冈把旅途里的心情寄回家。',
facts:['从去多哈的第一程就开始想给父母写信。','希望从梵蒂冈寄回家，觉得这样更有意义。','信里写到阿诺河、拉韦洛、马泰拉、罗马与《大卫》。','已知有信的草稿；是否实际寄出未确认。'],
core:["During my trip to Italy, I worked on a letter to my parents. I'd started thinking about it on the first leg of the journey to Doha, and I wanted to send it from the Vatican because that felt more meaningful than sending an ordinary message from my phone.","In the letter, I brought together different parts of the trip: the sunset over the Arno, the sea near Ravello, the changing evening colours in Matera, and Rome's ancient sites. I also wrote about the less comfortable parts, such as pulling my suitcase uphill on my own. I wanted the letter to contain something of what the journey had actually felt like."],
outline:['letter to parents · idea on journey to Doha','wanted to send it from the Vatican','Arno · Ravello · Matera · Rome','beautiful moments + difficult parts → honest account'],
phrases:[["I'd started thinking about it…",'过去完成时交代更早开始的念头'],['put my feelings into words','把感受化成文字'],['an honest account of…','真实讲述，而非完美旅行故事'],['something they could come back to','可以反复读到的东西']],
topics:[
{label:'写过的重要文字',question:'Describe something meaningful you wrote.',cues:['what you wrote','who it was for','why it mattered to you'],opening:"Something meaningful I wrote was a letter to my parents during my Italy trip. I wanted it to say more than a quick update about where I had been.",focus:'文字内容与为什么写是主线。用 wrote / wanted to send，避免说已寄到或父母读后反应。',detail:"Writing it made me choose which details mattered enough to include. The beautiful views were part of it, but so were the moments that had tested me or made me unexpectedly emotional.",ending:"That's why the letter mattered to me. It was a way of putting my feelings into words while the trip was still vivid, rather than reducing the experience to a list of destinations.",key:'letter → selected details → personal meaning'},
{label:'表达感谢',question:'Describe a time you expressed gratitude to someone.',cues:['who you wanted to thank','how you expressed your feelings','why you chose that way'],opening:"I'd like to talk about putting my gratitude to my parents into a letter during my trip to Italy. Writing felt like a better way to express a complicated feeling than a quick message.",focus:'选择写信表达感受，感谢只围绕草稿里已有的支持；不展开家庭冲突，也不编收信反应。',detail:"Alongside the travel memories, I tried to acknowledge the support behind my journey. I didn't want to use a grand, general statement and leave it there; the personal details helped explain what I was grateful for.",ending:"For me, the value was in taking the time to say it carefully. I can talk about what I wrote and intended to express, without needing to turn it into a story about someone's reaction.",key:'gratitude → concrete memories → careful expression'},
{label:'想送的特别礼物',question:'Describe a gift you would like to give someone.',cues:['who you would give it to','what the gift would be','why you think it would be meaningful'],opening:"A personal gift I'd like to give my parents is a letter from a meaningful place on my travels. I worked on one during my Italy trip and wanted to send it from the Vatican.",focus:'仅适配 would like to give。若题目问已经送出的礼物，先确认寄出事实再用。',detail:"What would make it a gift is the attention behind it. Instead of choosing an object, I'd be giving them an account of experiences and feelings they hadn't been there to share directly.",ending:"I'd like it to be something they could come back to later. The place it came from would make it special, but the personal details would be the main reason for sending it.",key:'intended gift → attention → lasting account'},
{label:'分享旅行经历',question:'Describe an occasion when you shared an experience in writing.',cues:['what experience you described','how you described it','why you chose to write about it'],opening:"An example I'd choose is writing about my Italy trip in a letter to my parents. I wanted to share both what I had seen and what travelling alone had felt like.",focus:'强调如何选择细节来分享经历。这里以写信为分享方式，不声称信件已送达。',detail:"I tried to balance the scenery with the experience of being there. A sunset tells one part of the story; feeling exhausted or unexpectedly moved tells another. Including both made the account feel more like my own trip.",ending:"Writing gave me room to connect those moments. It helped me express more than I could in a brief message, while keeping the account grounded in things that had actually happened.",key:'experience → scenery and feelings → why writing'}
],part3:[{q:'Do handwritten letters still have value?',guide:'时间投入与可保留性；也承认即时消息的方便。',a:"Yes, partly because writing a letter usually involves a deliberate choice to slow down. A letter can also become a physical reminder of a particular time. Messages are much more convenient for daily communication, but convenience isn't the only thing people value in a personal exchange."},{q:'Is an expensive gift always a better gift?',guide:'直接回答，再用关系与具体需要解释。',a:"No. A good gift depends on the person and the relationship. Something inexpensive can be meaningful if it reflects careful attention to someone's interests or a shared experience. Price can affect quality or usefulness, but it doesn't automatically measure how thoughtful the gift is."}]
}
];
